### ISSUE TITLE
Enable/Disable show of each group

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [partydragen/Members#14]
Simply add setting in member's StaffCP tab (`StaffCP > Members`) that you can select, from your **Groups** list (`StaffCP > Groups`) which groups will be shown

This is the list of my Groups from `StaffCP > Groups`.
Now what would be cool is that we can enable/disable showing for each of them, in that `StaffCP > Members` tab.
Why this, because as you can see I have some groups like "HeadAdmin", "Mod"...
But i have "podserver-factions" = this means (in English) "subserver-factions" and by adding this group to a user as a second group, I give him primary group as "Mod" or "Helper" which is his rank, and below that there will be SUBSERVERS where (s)he is that rank.
I hope you understand me, if not, I can elaborate, but this is pretty simple: I want to disable showing of some groups as not all of my groups are ranks on my server that I want to be displayed, and not all of them are used as primary user group ever.
![image](https://user-images.githubusercontent.com/56804505/86532589-86f40900-becb-11ea-83be-df69cb818826.png)
*I am using template but doesn't matter, the point matters*

**Comment by partydragen** [comment]
There i have added it, Will release this tomorrow right after pr9 is released
