### ISSUE TITLE
Custom created groups not clickable - not found on website

### ISSUE THREAD

**Issue by SupaYoshi** [partydragen/Members#15]
Hi,

Just updated to the latest Pr8 and updated the Members module! Working, however, we have two custom groups, Builders / Creators and Web developers.

When you click on these groups now on the website, it gives a 404 error.
1. Go to https://www.unitedfactions.net/members/
2. Click on Builders, you will be served this error page: https://prnt.sc/waxg5b

**Comment by SupaYoshi** [comment]
It might be because I used a / in one of the group names as "Builders / Creators", it was not being sanitized correctly. After changing the group to "Builders & Creators" it seems to be fixed!

**/ is not allowed in Group names!**

**Comment by partydragen** [comment]
Fixed, Will be included in next release
