### ISSUE TITLE
[Bug] Members module icon is incorrectly placed on mobile

### ISSUE THREAD

**Issue by matias-io** [partydragen/Members#21]
I have tried numerous attempts in various mobile environments; the members module icon always appears on the right when the others appear on the left as seen in my included screenshot. Additionally, The forms module does this as well (though it might just be the dropdown menu). This was tested on various templates and DefaultRevamp from pr9-pr10
![image](https://user-images.githubusercontent.com/69017144/124155027-0deaab80-da64-11eb-9675-54442b0c6d3b.png)

**Comment by partydragen** [comment]
All icons using same system, so only possible ways is templates and how you setup them
